id = "cohere-embed-v-4-0"

[capabilities.embeddings]
min_dimensions = 256
max_dimensions = 1536
default_dimensions = 1536

[modalities]
input = ["text", "image"]
output = ["text", "embedding"]

[extra]
type = "embedding"
